### ISSUE TITLE
replace flow with Typescript

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/react-flexview#40]
## requirements
replace flow with Typescript

## specs
...

**Comment by joelbowen** [comment]
I'm curious what the reason for this would be? Having used both on large production apps I have a great appreciation for TypeScript and Flow, but what's the driving motivation to switch in your case?

**Comment by FrancescoCioria** [comment]
Honestly, for `FlexView` itself there isn't a real motivation.
I'm planning to refactor it in TypeScript because at buildo (our organization), after a long analysis (the refactor of `FlexView` in flow was part of this analysis), we decided to use TypeScript. 

We opted for TypeScript in our projects instead of flow because we found it to be better integrated with React, more stable and better maintained.
