### ISSUE TITLE
Module not found: can't resolve `react-flexview/lib/flexView.css`

### ISSUE THREAD

**Issue by MateYoutility** [buildo/react-flexview#50]
Hi,
i want install this fantastic library, i have read the readme and when i have write in my App.js:
```js
import 'react-flexview/lib/flexView.css' // FlexView is useless without its style
```

I have recive this error:
```
./src/App.js
Module not found: Can't resolve 'react-flexview/lib/flexView.css' in ...
```

Do you have any idea for this problem?

P.S. into node_modules/react-flexview/lib/ i don't find flexView.css

Thank you so much

**Comment by FrancescoCioria** [comment]
Hi @MateYoutility

it appears that after thew refactor in TS we're no longer transpiling the SASS file in CSS in the `lib` directory... definitely a bug!
Thanks for the report, I'll fix it asap
