### ISSUE TITLE
more justify/align props?

### ISSUE THREAD

**Issue by contra** [buildo/react-flexview#70]
seems like you can't do `justify-content: space-between` or `justify-content: space-around` 

```
Failed prop type: Invalid prop `hAlignContent` of value `space-between` supplied to `FlexView`, expected one of ["left","center","right"]
```

also seems to be a lot of other missing aspects of flexbox or limited property values. is this something you would take a PR to fix or is this intended?

**Comment by ashubham** [comment]
@giogonzo Please share your thoughts on this issue. This seems to be a library limitation.

**Comment by contra** [comment]
@ashubham Sorry I just ended up writing our own thing - https://github.com/staeco/react-flex-lite
