### ISSUE TITLE
Remove lodash deps

### ISSUE THREAD

**Issue by CupCakeArmy** [buildo/react-flexview#72]
It should be possible to do this without lodash.
according to [bundlephobia](https://bundlephobia.com/result?p=react-flexview@4.0.2) the package is `23.6kB` minified and `7.5kb` gzipped. which is insane.

Other than that you are the only guys to include flex direction 🎉❤️

**Comment by FrancescoCioria** [comment]
👍 yes, I guess we could easily remove `lodash`, I'll open a PR shortly
