### ISSUE TITLE
Allow to pass a ref for the underlying div

### ISSUE THREAD

**Issue by veej** [buildo/react-flexview#80]
## Description
At the moment it's impossible to pass a `ref` to the underlying div element.
We should add an `innerRef` prop to `FlexView` and forward it as ref for the root div.

**Comment by giogonzo** [comment]
slightly different proposal: use `forwardRef` and update the `ref` typings as appropriate to refer to the underlying `<div />`. Rationale: no need to have a reference to the `View` element itself (no API exposed as instance methods), while you often need a ref to the underlying div to do dirty DOM stuff

**Comment by giogonzo** [comment]
Even better: since `FlexView` has no "public API" on the class/component instance, no need to expose the ref to `FlexView` at all. Exposing the one to the underlying `div` is more than enough, as in:

```ts
type FlexViewProps = {
  // ... more props
  ref: React.Ref<HTMLDivElement>
}
```
